---
- name: Ensure required packages are installed
  ansible.builtin.include_role:
    name: common
    tasks_from: fastpackages
  vars:
    packages_list:
      - firewalld

- name: Enable and start the firewalld service
  become: true
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: started

- name: "Configure firewall ports"
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - "{{ keycloak_http_port }}/tcp"
    - "{{ keycloak_https_port }}/tcp"
