---
- name: Validate parameters
  ansible.builtin.assert:
    that:
      - nginx.service_name is defined
      - nginx.key_file is defined
      - nginx.crt_file is defined
      - nginx.csr_file is defined
      - nginx.siteconf_file is defined
      - nginx_ssl_generate_self_signed_certs is defined
    quiet: true
  tags:
    - nginx

- name: "Install packages: {{ nginx_prereq_package_list }}"
  become: true
  ansible.builtin.dnf:
    name: "{{ nginx_prereq_package_list }}"
    state: present
  when:
    - nginx_prereq_package_list  | default([]) | length > 0
  tags:
    - nginx

- name: Ensure nginx conf.d contents are removed
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/etc/nginx/conf.d/*"
  tags:
    - nginx

- name: Ensure nginx in a running state
  ansible.builtin.systemd:
    name: nginx
    state: started
  register: nginxDetails
  until: nginxDetails.status.ActiveState == "active"
  retries: 10
  delay: 3
  tags:
    - nginx

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  become: true
  command: setsebool httpd_can_network_connect on -P
  when:
    - nginx_httpd_can_network_connect_enabled == True
  tags:
    - nginx
    - setsebool

- name: Stat nginx configuration
  stat:
    path: /etc/nginx/nginx.conf
  register: conf_org
  tags:
    - nginx

- name: Stat nginx configuration
  stat:
    path: /etc/nginx/nginx.conf.org
  register: conf_backup
  tags:
    - nginx

- name: Backup nginx configuration
  copy:
    src: "{{ conf_org.stat.path }}"
    dest: "{{ conf_backup.stat.path }}"
  when: conf_backup.stat.exists == False
  tags:
    - nginx

- name: Include OpenSSL for Selfsigned certificate
  ansible.builtin.include_tasks: openssl.yml
  tags:
    - nginx
    - openssl
  when: (nginx_ownca_enabled is defined and nginx_ownca_enabled == False) or nginx_ownca_enabled is undefined

- name: Include Ownca Authority
  block:
    - name: Include Ownca Authority for selfigned certificates
      ansible.builtin.include_tasks: ownca.yml
      tags:
        - nginx
        - openssl

    - name: Include Ownca OpenSSL for Selfsigned certificate
      ansible.builtin.include_tasks: ownca_openssl.yml
      tags:
        - nginx
        - openssl
  when: nginx_ownca_enabled is defined and nginx_ownca_enabled == True

- name: "Configure nginx server conf file"
  template:
    src: 'server.conf.j2'
    dest: "{{ nginx.siteconf_file }}"
    group: 'root'
    owner: 'root'
    mode: '0644'
  register: nginx_register_nginx_config
  notify:
    - Test nginx and reload
  tags:
    - nginx

- name: PPatch the nginx config file 'worker_connections'
  ansible.builtin.replace:
    dest: "{{ conf_org.stat.path }}"
    regexp: '^(.*){{ item.regexp }}(.*)$'
    replace: '{{ item.replace }}'
    owner: nginx
    group: nginx
    mode: 644
  with_items:
    - { regexp: 'worker_connections', replace: '     worker_connections 4096;' }
  notify:
    - Test nginx and restart
  tags:
    - nginx

- name: Flush handlers
  meta: flush_handlers