---
- name: Create nginx private directory
  file:
    path: "{{ nginx_ssl_private_dir }}"
    state: directory
    owner: nginx
    group: nginx
    mode: 0775
    recurse: yes
  tags:
    - nginx
    - openssl

- name: Ensure absence old files if exists
  become: true
  ansible.builtin.file:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ nginx.key_file }}" 
    - "{{ nginx.csr_file }}" 
    - "{{ nginx.crt_file  }}" 
  tags:
    - nginx
    - openssl

- name: Generate RSA Key
  command: >
      openssl 
      genrsa  
      -out "{{ nginx.key_file }}" 
      2048
  args:
    creates: "{{ nginx.key_file }}"
  tags:
    - nginx
    - openssl

- name: Generate CSR (Used to create Company signed Key)
  command: >
    openssl req 
    -new 
    -subj "/C=US/ST=CT/L=East Hartford/O={{nginx.ssl.organization_name}}/CN={{nginx.ssl.common_name}}"
    -key "{{ nginx.key_file }}"
    -out "{{ nginx.csr_file }}"
  args:
    creates: "{{ nginx.csr_file }}"
  tags:
    - nginx
    - openssl

- name: Generate Self-signed Certificate
  command: >
    openssl req 
    -x509 
    -days 3650 
    -key "{{ nginx.key_file }}"
    -in "{{ nginx.csr_file }}"
    -out "{{ nginx.crt_file }}"
  args:
    creates: "{{ nginx.crt_file }}"
  tags:
    - nginx
    - openssl