---
### Mysql settings
mysql_hide_passwords: true

# database name, this is a required variable
mysql_database_name: stigman

# database user, this is a required variable
mysql_user_name: stigman

# user password, this is a required variable
mysql_user_password: ''

# database root user, this is a required variable
mysql_root_username: root

#
mysql_data_dir: /var/lib/mysql


### Mysql configuration settings
mysql_sort_buffer_size: 64M
mysql_innodb_buffer_pool_size: 2G
