---
nginx: # noqa var-naming this is an internal dict of interpolated values
  service_name: "nginx"
  ssl_private_dir: "{{ nginx_ssl_dir }}/private"
  certificate_file: "{{ nginx_ssl_dir }}/{{ nginx_site_name }}.crt"
  key_file: "{{ nginx_ssl_dir }}/private/{{ nginx_site_name }}.key" 
  siteconf_file: "{{ nginx_siteconf_dir }}/{{ nginx_site_name }}.conf"
  cofig_dir: /etc/nginx/conf.d/{{ nginx_site_name }}.conf
  
