---
- name: Ensure required package firewalld are installed
  ansible.builtin.include_tasks: fastpackages.yml
  vars:
    packages_list:
      - firewalld
  tags:
    - keyclaok

- name: Enable and start the firewalld service
  become: true
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: started
  tags:
    - keyclaok

- name: "Configure firewall for {{ keycloak.service_name }} ports"
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - "{{ keycloak_http_port }}/tcp"
    - "{{ keycloak_https_port }}/tcp"
    - "{{ keycloak_jgroups_port }}/tcp"
  tags:
    - keyclaok
