---
### STIG Manager Watcher

## Manual download
# curl -OL https://github.com/NUWCDIVNPT/stigman-watcher/releases/download/1.4.4/stigman-watcher-linux-1.4.4.tar.gz

## Configuration specific to stigman watcher
stigman_watcher_pkg: tar.gz
stigman_watcher_version: 1.4.4
stigman_watcher_archive: "stigman-watcher-linux-{{ stigman_watcher_version }}.{{ stigman_watcher_pkg }}"
stigman_watcher_download_url: "https://github.com/NUWCDIVNPT/stigman-watcher/releases/download/{{ stigman_watcher_version }}/{{ stigman_watcher_archive }}"
stigman_watcher_installdir: "{{ stigman_watcher_dest }}/stigman-watcher-{{ stigman_watcher_version }}"

# whether to install from local archive
stigman_watcher_offline_install: true

# Athentication strategy
stigman_watcher_auth_strategy: client_id

### Install location and service settings
stigman_watcher_dest: /opt
stigman_watcher_home: "{{ stigman_watcher_installdir }}"
stigman_watcher_service_user: stigman
stigman_watcher_service_group: stigman
stigman_watcher_service_restart_always: true
stigman_watcher_service_restart_on_failure: true
stigman_watcher_service_restartsec: "60s"
stigman_watcher_config_file: "{{ stigman_watcher_home }}/.env"

stigman_watcher_hostname: localhost
stigman_watcher_http_port: 8080
stigman_watcher_force_health_check: true    #depecated - stigman_watcher_health_check_enabled
stigman_watcher_health_check_url_path:

### Using Default Configuration
stigman_watcher_add_existing: true
stigman_watcher_api_base: http://localhost:54000/api
stigman_watcher_authority: http://localhost:8080/realms/stigman
stigman_watcher_cargo_delay: 2000
stigman_watcher_cargo_size: 25

## Authentication using client_id
stigman_watcher_client_id: stigman-watcher
stigman_watcher_client_secret: 954fd71a-dad6-47ab-8035-060268f3d396

# Authentication using client_key
stigman_watcher_client_key: 
stigman_watcher_client_key_passphrase: 

stigman_watcher_collection: 1
stigman_watcher_create_objects: true
stigman_watcher_ignore_globs: "**/ignoredDir,**/someDir/ignoredFile"
stigman_watcher_log_file: "logs/watcher.log"
stigman_watcher_log_file_level: debug
stigman_watcher_history_file: "history.log"
stigman_watcher_log_level: info

#
stigman_watcher_path: ["./watched", "//unc/path"]

#
stigman_watcher_use_polling: false
stigman_watcher_stability_threshold: 5000
stigman_watcher_mode: events


# http://localhost:54000/api/api/op/definition