---
nginx_install_service: true

nginx_openssl_conf: "{{ role_path }}/openssl.conf"

nginx_ssl_dir: "/etc/pki/nginx"

nginx_site_name: "eh-stigman-1"

nginx_siteconf_dir: "/etc/nginx/conf.d"

nginx_ssl_override_filename: localhost

nginx_ssl_generate_self_signed_certs: true
