---
- name: Restart and enable service
  ansible.builtin.systemd:
    name: "{{ watcher.service_name }}"
    enabled: true
    state: restarted
    daemon_reload: true
  become: true
  tags:
     - watcher

- name: Wait until service becomes active
  ansible.builtin.uri:
    url: "{{ watcher.health_url }}"
  register: watcher_status
  until: watcher_status.status == 200
  retries: 5
  delay: 3
  when: internal_force_health_check | default(true)
  tags:
     - watcher
