# - name: Generate a Private Key
#   command: >
#     openssl genpkey 
#       -algorithm RSA 
#       -out private_key.pem 
#       -pkeyopt rsa_keygen_bits:2048
#   register: private_key
#   tags:
#     - jwt

# - debug:
#     var: private_key

# - name: Generate Public Key
#   command: >
#     openssl rsa 
#       -pubout 
#       -in private_key.pem 
#       -out public_key.pem
#   when:
#     - private_key.rc == 0
#   tags:
#     - jwt

# - name: Create a certificate
#   command: >
#     openssl req 
#       -new 
#       -x509 
#       -key private_key.pem 
#       -out cert.pem 
#       -days 3650
#   when:
#     - private_key.rc == 0
#   register: cert_pem
#   tags:
#     - jwt

# - name: Create pkcs12 archive
#   command: >
#     openssl pkcs12 
#       -export 
#       -out keystore.p12 
#       -inkey private_key.pem 
#       -in cert.pem 
#       -name mykey
#   when:
#     - private_key.rc == 0
#     - cert_pem.rc == 0
#   tags:
#     - jwt

- name: Create/Update client (keycloak).
  debug:
    msg:
      - "1. Enter your relm"
      - "2. Go to Clients"
      - "3. Turn on Client authentication and enable Service accounts roles authentication flow."

- name: Set credential type to rs256 signed JWT (keycloak)..
  debug:
    msg:
      - "1. Go to 'Client Scopes' and set desired scopes."
      - "2. Go to 'Credentials' and selected Signed Jwt with RS256"

- name: Import keys (keycloak).
  debug:
    msg:
      - "1. Go to Client -> Keys -> Import."
      - "2. Archive Format: PKCS#12"
      - "3. Store Password: **********"
      - "4. Import File: keystore.p12"