---
- name: Clean server installation
  hosts: localhost
  gather_facts: true
  become: yes
  become_method: sudo  
  ignore_errors: true
  
  tasks:
    - name: Ensure all services are stopped & disabled
      become: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: false
        state: stopped
      with_items:
        - mysqld
        - keycloak
        - stigman
        - nginx

    - name: Ensure removal of persistent facts from ansible.builtin.set_fact
      ansible.builtin.meta: clear_facts


    - name: Ensure absence of kecloak
      become: true
      ansible.builtin.file:
        name: "{{ item }}"
        state: absent
      with_items:
        - /etc/ansible/facts.d/keycloak.fact
        - /etc/sysconfig/keycloak
        - /etc/systemd/system/keycloak.service
        - /opt/keycloak-24.0.4/
        - /opt/keycloak-24.0.4.tar.gz


    - name: Ensure absence of stig-manager
      become: true
      ansible.builtin.file:
        name: "{{ item }}"
        state: absent
      with_items:
        - /etc/systemd/system/stigman.service
        - /opt/stig-manager-1.4.12/
        - /opt/stig-manager-linux-1.4.12.tar.xz

    - name: Delete old nginx configuration before restore
      ansible.builtin.file:
        path: /etc/nginx/nginx.conf
        state: absent

    - name: Restore nginx configuration
      copy:
        src: /etc/nginx/nginx.conf.org
        dest: /etc/nginx/nginx.conf

    - name: Ensure absence of nginx
      become: true
      ansible.builtin.file:
        name: "{{ item }}"
        state: absent
      with_items:
        - /etc/pki/nginx/eh-stigman-1.crt
        - /etc/pki/nginx/private/eh-stigman-1.key







