---
- name: Start STIG Manager intallation playbooks
  hosts: stigman
  gather_facts: true
  become: yes
  become_method: sudo
  vars:
    offline_install: true
    mysql_stigman_password: "Password123!"
    stigman_admin_password: "Password123!"

  #vars_prompt:
     #- name: stigman_admin_password
     #  prompt: Enter the Admin Password for Keycloak
     #- name: mysql_stigman_password
     #  prompt: Enter the DB Password for Stigman User

  tasks:
    - command: hostname -f
      register: result
      tags:
        - always

    - name: Include MySQL
      include_role:
        name: mysql
      vars:
        # mysql_user_name: stigman
        # mysql_database_name: stigman
        #mysql_data_dir: /data/mysql
        mysql_user_password: "{{ mysql_stigman_password }}"
      tags:
        - mysql
        
    - name: Include Keycloak
      include_role:
        name: keycloak
      vars:
        keycloak_admin_pass: "{{ stigman_admin_password }}"
        keycloak_offline_install: "{{ offline_install }}"
        keycloak_hostname_backchannel_dynamic: true
        keycloak_hostname_strict: false
        keycloak_hostname_strict_https: false
      tags:
        - keycloak

    - name: Include keycloak role
      include_role:
        name: keycloak_realm
      vars:
        keycloak_admin_pass: "{{ stigman_admin_password }}"
        keycloak_offline_install: true
      tags:
        - keycloak_realm

    - name: Include Ngix role
      include_role:
        name: nginx
      vars:
        country: 'US'                           # C
        state: 'CT'                             # ST
        locality: 'Trenton'                     # L
        organization: 'ACME'                    # O
        organization_unit: 'IT'                 # OU
        common_name: '{{ ansible_hostname }}'   # CN
        email_address: 'info@example.com'       # emailAddress
        nginx_ownca_enabled: true
      tags:
        - nginx
        - openssl
        - setsebool

    - name: Include STIG Manager role
      include_role:
        name: stig-manager
      vars:
        stigman_classification: 'U'
        stigman_db_user: stigman
        stigman_db_seed_enabled: true
        stigman_db_password: "{{ mysql_stigman_password }}"
        stigman_offline_install: "{{ offline_install }}"
      tags:
        - stig-manager
        - seed

    - name: Include Stigman Watcher role
      include_role:
        name: stigman-watcher
      vars:
        watcher_add_existing: true
        watcher_api_base: http://localhost:54000/api
        watcher_authority: http://localhost:8080/realms/stigman
        watcher_offline_install: "{{ offline_install }}"
      tags:
        - stigman-watcher
        - watcher
        - jwt

    - name: Ensure services are restarted
      become: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: restarted
        daemon_reload: true
      with_items:
        - mysqld
        - keycloak
        - nginx
        - stigman
        - watcher
      tags:
        - nginx
