---
- name: Start STIG Manager intallation playbooks
  hosts: localhost
  gather_facts: true
  become: yes
  become_method: sudo
  vars:
    server_hostname: "{{ ansible_facts['hostname'] | default('localhost') }}"
    offline_install: true
    mysql_stigman_password: "Password123!"
    stigman_admin_password: "Password123!"

  #vars_prompt:
     #- name: stigman_admin_password
     #  prompt: Enter the Admin Password for Keycloak
     #- name: mysql_stigman_password
     #  prompt: Enter the DB Password for Stigman User

  tasks:
    - name: Include MySQL
      include_role:
        name: mysql
      vars:
        # mysql_user_name: stigman
        # mysql_database_name: stigman
        mysql_data_dir: /data/mysql
        mysql_user_password: "{{ mysql_stigman_password }}"
      tags:
        - mysql
        
    - name: Include Keycloak
      include_role:
        name: keycloak
      vars:
        keycloak_admin_pass: "{{ stigman_admin_password }}"
        keycloak_offline_install: "{{ offline_install }}"
        keycloak_hostname_backchannel_dynamic: true
        keycloak_hostname_strict: false
        keycloak_hostname_strict_https: false
      tags:
        - keycloak

    - name: Include keycloak role
      include_role:
        name: keycloak_realm
      vars:
        keycloak_admin_pass: "{{ stigman_admin_password }}"
        keycloak_offline_install: true
      tags:
        - keycloak_realm

    - name: Include Ngix
      include_role:
        name: nginx
      vars:
        #nginx_ssl_dir: "/etc/pki/nginx"
        nginx_site_name: "eh-stigman-1"
        nginx_ssl_generate_self_signed_certs: true
      tags:
        - nginx
        - openssl
        - setsebool

    - name: Include STIG Manager 
      include_role:
        name: stig-manager
      vars:
        stigman_hostname: 'eh-stigman-1'
        stigman_classification: 'U'
        stigman_db_user: stigman
        stigman_seed_db_enabled: true
        stigman_offline_install: "{{ offline_install }}"
        stigman_db_password: "{{ mysql_stigman_password }}"

        ## Customize 
        # stigman_client_welcome_image:
        # stigman_client_welcome_link:
        # stigman_client_welcome_message:
        # stigman_client_welcome_title:
      tags:
        - stig-manager

    - name: Include Stigman Watcher
      include_role:
        name: stigman-watcher
      vars:
        stigman_watcher_add_existing: true
        stigman_watcher_api_base: http://localhost:54000/api
        stigman_watcher_authority: http://localhost:8080/realms/stigman
        stigman_watcher_offline_install: "{{ offline_install }}"
      tags:
        - stigman-watcher
        - watcher



