---
- name: Run all STIG Manager Playbooks
  hosts: localhost
  gather_facts: true
  become: yes
  become_method: sudo
  # vars_prompt:
  #   - name: admin_pass_keycloak
  #     prompt: Enter the Admin Password for Keycloak
  #   - name: stigman_pass_mysql
  #     prompt: Enter the DB Password for Stigman User

  tasks:
    - name: Include MySQL
      include_role:
        name: mysql
      vars:
        # mysql_user_name: stigman
        # mysql_database_name: stigman
        # mysql_data_dir:
        mysql_user_password: "Password123!"
        # mysql_user_password: "{{ stigman_pass_mysql }}"
        
    - name: Include Keycloak
      include_role:
        name: keycloak
      vars:
        keycloak_admin_pass: "Password123!"
        # keycloak_admin_pass: "{{ admin_pass_keycloak }}"
        keycloak_offline_install: false
        keycloak_hostname_backchannel_dynamic: true
        keycloak_hostname_strict: false
        keycloak_hostname_strict_https: false

    - name: Include keycloak role
      include_role:
        name: keycloak_realm
      vars:
        keycloak_admin_pass: "Password123!"
        #keycloak_admin_pass: "{{ admin_pass_keycloak }}"
        keycloak_offline_install: true

    - name: Include Ngix
      include_role:
        name: nginx
      vars:
        nginx_openssl_conf: "{{ role_path }}/openssl.conf"
        nginx_ssl_dir: "/etc/pki/nginx"
        nginx_site_name: "eh-stigman-1"
        nginx_ssl_override_filename: localhost
        nginx_ssl_generate_self_signed_certs: true

    - name: Include STIG Manager 
      include_role:
        name: stig-manager
      vars:
        stigman_classification: U
        #stigman_oidc_provider: http://localhost:8080/realms/stigman
        #stigman_client_oidc_provider: http://localhost:8080/realms/stigman

        # DB
        stigman_db_user: stigman
        stigman_db_password: "Password123!"
        # stigman_db_password: "{{ stigman_pass_mysql }}"

        # Customize 
        # stigman_client_welcome_image:
        # stigman_client_welcome_link:
        # stigman_client_welcome_message:
        # stigman_client_welcome_title:

    - name: Include Stigman Watcher
      include_role:
        name: stigman-watcher
      vars:
        stigman_watcher_auth_strategy: client_id
        stigman_watcher_add_existing: true
        stigman_watcher_api_base: http://localhost:54000/api
        stigman_watcher_authority: http://localhost:8080/realms/stigman

